version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    networks:
      - main

networks:
  main:
    driver: bridge
